
package butters.rules2.map;

import butters.rules2.map.RulesContext;
import butters.rules2.LeftNode;
import butters.rules2.RightNode;


import org.w3c.dom.Node;
import org.w3c.dom.Element;
import org.w3c.dom.Document;

import java.lang.System;


dialect  "mvel"

global RulesContext $app;

rule "map element to element"
when
    $l: LeftNode(value.nodeType == 1)  // element
    $r: RightNode(value.nodeType == 1, !value.hasChildElement)
    
then
    $app.getLogger().info("mapping: element to element: " + $r.value + " -->> " + $l.value);
    $app.replaceWithValueof($r.value, $l.value);
end
